apiVersion: v1
kind: Service
metadata:
  name: spring3-devsecops
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring3-devsecops
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring3-devsecops
  name: spring3-devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring3-devsecops
  template:
    metadata:
      labels:
        app: spring3-devsecops
      name: spring3-devsecops
    spec:
      containers:
      - image: 10.12.1.20:8086/com.maryanto.dimas.example/spring3-devsecops-example:fb188de0
        imagePullPolicy: IfNotPresent
        name: spring3-devsecops
        ports:
        - containerPort: 8080
      restartPolicy: Always
